### ISSUE TITLE
bitwise '|' with boolean operands in anabatic

### ISSUE THREAD

**Issue by robtaylor** [lip6/coriolis#42]
../anabatic/src/Dijkstra.cpp:695:14: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
    else if (gcell->isStrut()| gcell->isMatrix() )   return ((gcell->getWidth() > gcell->getHeight())||(gcell->getWidth() == gcell->getHeight()));

**Comment by jpc-lip6** [comment]
Fixed in #41  (#3d8d737a). Just a typo.
