### ISSUE TITLE
Publishing of main branch wheels to test PyPi is not working

### ISSUE THREAD

**Issue by rossmotley** [lip6/coriolis#89]
Looks like the publishing of the python wheels to test pypi is failing. It seems to be due to the version of the PyPi package being fixed at 2.5.5 and not being generated dynamically.

From [a recent job](https://github.com/lip6/coriolis/actions/runs/6864907722/job/18668057888):

> Uploading 
coriolis_eda-2.5.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

...

> ERROR HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
> File already exists. See https://test.pypi.org/help/#file-name-reuse for more information.

In the past some sort of dynamic versioning looks like it was happening, as there are versions like `2.5.5a61` [in test pypi](https://test.pypi.org/project/coriolis-eda/#history).

**Comment by Coloquinte** [comment]
It's working now. Multiple publications with the same git commit are not supported, so we only publish from main. Since I tested it separately it's gonna crash the first time on main [here](https://github.com/lip6/coriolis/actions/runs/7112901230)

**Comment by rossmotley** [comment]
I can confirm that [intermediate builds are in the test pypi again](https://test.pypi.org/project/coriolis-eda/2.5.4a156/).
